const express = require("express");
const oracledb = require("oracledb");
oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
const app = express();
const cors = require("cors");
const port = 3000;

app.use(cors());
app.use(express.json());

const dbConfig = {
  user: "EstebanSanchez",
  password: "202300769",
  connectString: "172.17.0.2:1521/XEPDB1",
};

// 1. OBTENER USUARIO POR ID (GET)
app.get("/usuarios/:id", async (req, res) => {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    const result = await connection.execute(
      `SELECT * FROM usuarios WHERE id = :id`,
      [req.params.id],
    );
    res.json(result.rows);
  } catch (err) {
    res.status(500).send(err.message);
  } finally {
    if (connection) await connection.close();
  }
});

// 1.1 OBTENER TODOS LOS USUARIOS (GET)
app.get("/usuarios", async (req, res) => {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    const result = await connection.execute(`SELECT * FROM usuarios`);
    res.json(result.rows);
  } catch (err) {
    res.status(500).send(err.message);
  } finally {
    if (connection) await connection.close();
  }
});

// 2. INSERTAR USUARIO (POST)
app.post("/usuarios", async (req, res) => {
  let connection;
  const { nombre, correo } = req.body;
  try {
    connection = await oracledb.getConnection(dbConfig);
    await connection.execute(
      `INSERT INTO usuarios (nombre, correo) VALUES (:1, :2)`,
      [nombre, correo],
    );
    await connection.commit();
    res.status(201).send("Usuario creado");
  } catch (err) {
    res.status(500).send(err.message);
  } finally {
    if (connection) await connection.close();
  }
});

// 3. ELIMINAR USUARIO (DELETE)
app.delete("/usuarios/:id", async (req, res) => {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    await connection.execute(`DELETE FROM usuarios WHERE id = :id`, [
      req.params.id,
    ]);
    await connection.commit();
    res.send("Usuario eliminado");
  } catch (err) {
    res.status(500).send(err.message);
  } finally {
    if (connection) await connection.close();
  }
});

// 4. CREAR TABLA DE USUARIOS (POST)
app.post("/setup", async (req, res) => {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);

    // Sentencia SQL para la tabla solicitada
    const sqlCreate = `
      CREATE TABLE usuarios (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        nombre VARCHAR2(50),
        correo VARCHAR2(50),
        PRIMARY KEY (id)
      )
    `;

    await connection.execute(sqlCreate);
    res.status(201).send("Tabla 'usuarios' creada exitosamente en Oracle.");
  } catch (err) {
    if (err.errorNum === 955) {
      // ORA-00955: name is already used by an existing object
      res.status(400).send("La tabla ya existe en la base de datos.");
    } else {
      res.status(500).send("Error al crear la tabla: " + err.message);
    }
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
});

app.listen(port, () => {
  console.log(`Servidor API escuchando en http://localhost:${port}`);
});
